[project]
name = "InterfaceTestingFramework"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "阿康", email = "akyaaaaa@163.com"},
]
dependencies = ["pytest>=8.3.5"]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
