# Generated by Django 5.2 on 2025-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("method", models.CharField(max_length=10)),
                ("url", models.CharField(max_length=255)),
                ("body", models.JSONField(blank=True, null=True)),
                ("expected_status_code", models.IntegerField()),
                ("expected_response", models.JSONField(blank=True, null=True)),
                (
                    "root_url",
                    models.CharField(default="https://reqres.in", max_length=255),
                ),
            ],
        ),
    ]
